server:
  port:10005

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@mitem714285.iptime.org:1521:XE
    username: hr
    password: TestPassword
  jpa:
    hibernate:
#        Hibernate의 ddl-auto 옵션
#          - create: 설계 단계에 사용. 앱 실행시 매핑된 테이블 삭제하고 새로 만든다. 실제 서비스 중인 프로젝트에선 사용금지
#          - create-drop: create와 동일하나, 앱 종료시 테이블을 삭제.
#          - none: Hibernate가 ddl에 관여하지 않음. ddl-auto를 선언하지 않아도 동일하게 작동.
#          - update: 앱 실행시 매핑된 테이블과 엔티티객체가 동일한지 확인. 컬럼 수정, 추가 같은 변경사항이 있을시 테이블에 적용하며, 기존 데이터는 유지된다. (단, 컬럼 삭제는 불가능)
#          - validate: 앱 실행시, 매핑된 테이블이 엔티티와 동일한지 검증. 일치하지 않을 시 실행되지 않음. (단, 컬럼이 더 적은것에 대해 한해서)
#      ddl-auto: create
#      ddl-auto: create-drop
#      ddl-auto: update
      ddl-auto: validate